languageCode: en-us
enableRobotsTXT: true
baseurl: "https://karijndenteuling.com/"  # Include trailing slash
title: Karijn Den Teuling
theme: "newsroom"
author: Karijn Den Teuling
copyright: "Copyright © 2019, Weru and the Hugo Authors; all rights reserved."
canonifyurls: true
paginate: 3
# Enable syntax highlighting
# comment or delete the following lines 11 ~ 14
pygmentsCodefences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
pygmentsOptions: "linenos=table"

  