baseURL: http://vandijke.xyz
languageCode: en-us
theme: "PaperMod"
title: vandijke.xyz
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: vandijke.xyz
  description: "Personal landing page of Martyn van Dijke"
  keywords: [Blog, Portfolio, PaperMod]
  author: Martyn van Dijke
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.png"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  profileMode:
      enabled: true
      title: "Enthusiast selfhoster by nature"
      subtitle: "Currently working as a DevOps Engineer @ ASML"
      imageUrl: "/favicon.png"
      imageTitle: "<title of image as alt>"
      imageWidth: 120 # custom size
      imageHeight: 120 # custom size
      buttons:
        - name: heimdall
          url: "https://heimdall.vandijke.xyz/"

  socialIcons: # optional
      - name: "github"
        url: "https://github.com/martynvdijke"
      - name: "instagram"
        url: "https://instagram.com/martynvandijke"
      - name: "linkedin"
        ulr: "https://linkedin.com/in/martynvandijke"

menu:
  main:
    - identifier: projects
      name: projects
      url: /projects/
      weight: 20
    - identifier: blog
      name: blog
      url: /blog/
      weight: 20
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30