baseURL: http://vandijke.xyz
languageCode: en-us
title: vandijke.xyz
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: false
  # Used as meta data; describe your site to make Google Bots happy 
  description: 
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logo.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Hi, I am Martyn van Dijke
    # Hero subtitle (optional)
    subtitle: A Electrical Engineering master student.
    # Button text
    buttontext: Get in touch
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/worker3.svg
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
    # - title: Blog
    #   url: /blogs
    # - title: Pricing
    #   url: /
    # button: true
  section1:
    title: Projects
    subtitle: Open source projects I made over the years.
    tiles:
    - title: Stargazer
      text: MILP optimization of energy market Simulation of day ahead energy market.
      icon: 048-electricity
      url: https://github.com/martynvdijke/Stargazer
      buttonText: Github
    - title: Gr-lora_sdr
      text: Implementing a multi-stream LoRa gateway in GNU Radio.
      icon: 004-signal
      buttonText: Github
      url: https://github.com/martynvdijke/gr-lora_sdr
  # section4:
  #   title: Features
  #   subtitle: with great responsibility
  #   tiles:
  #   - title: App builder
  #     icon: mouse-globe
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Free trial
  #   - title: Cloud integration
  #     icon: laptop-cloud
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Get started
  #   - title: Add-ons & plugins
  #     icon: plug-cloud
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Get started
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: logo.svg
    # Social Media Title
    socialmediatitle: Socials
    # Social media links (GitHub, Twitter, etc.). All are optional.
    # Icons are from Font Awesome
    socialmedia:
    - link: https://github.com/martynvdijke
      icon: github
    - link: https://facebook.com/MartynvanDijke
      icon: facebook
    - link: https://instagram.com/martynvandijke
      icon: instagram
    - link: https://linkedin.com/in/martynvandijke
      icon: linkedin
