baseURL: https://vandijke.xyz
languageCode: en-us
theme: "PaperMod"
title: vandijke.xyz
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: vandijke.xyz
  description: "Personal landing page of Martyn van Dijke"
  keywords: [Blog, Portfolio, PaperMod]
  author: Martyn van Dijke
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    favicon: "/favicon.png"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  profileMode:
      enabled: true
      title: "Enthusiast selfhoster by night, DevOps engineer at day."
      subtitle: "Homepage of Martyn van Dijke"
      imageUrl: "/favicon.png"
      imageTitle: "logo"
      imageWidth: 120 # custom size
      imageHeight: 120 # custom size
      buttons:
        - name: homer
          url: "https://homer.vandijke.xyz/"

  socialIcons: # optional
      - name: "github"
        url: "https://github.com/martynvdijke"
      - name: "instagram"
        url: "https://instagram.com/martynvandijke"
      - name: "linkedin"
        ulr: "https://linkedin.com/in/martynvandijke"

  outputs:
      home:
          - HTML
          - RSS
          - JSON # is necessary
menu:
  main:
    - name: Archive
      url: archives
      weight: 5
    - name: Search
      url: search/
      weight: 10
    - identifier: projects
      name: projects
      url: projects/
      weight: 20
    - name: Tags
      url: tags/
      weight: 10