name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Install hugo
        run: sudo apt-get install hugo -y
      - name: Hugo build
        run: sudo apt-get install hugo -y
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag martynvandijke/vandijke.xyz:latest
      - name: Push Docker image
        run: docker push martynvandijke/vandijke.xyz:latest
