name: Build Docker image

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Install hugo
        run: wget https://github.com/gohugoio/hugo/releases/download/v0.122.0/hugo_0.122.0_linux-amd64.deb && dpkg -i hugo_0.122.0_linux-amd64.deb
      - name: Hugo build
        run: hugo
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag martynvandijke/vandijke.xyz:latest
      - name: Push Docker image
        run: docker push martynvandijke/vandijke.xyz:latest

